### ISSUE TITLE
게임 일시정지 구현 & 레벨업 시 스킬트리 선택 구현

### ISSUE THREAD

**Issue by bu-mang** [Bumang-Cyber/Phaser3-VampireSurvivor#1]
# TODO:
- [ ] 게임 일시정지 구현
- [ ] 레벨업 시 스킬트리 선택 UI 마크업
- [ ] 레벨업 시 스킬트리 선택 기능 구현
